### ISSUE TITLE
Recipe 'jsreport-text' not found

### ISSUE THREAD

**Issue by mkosett123321** [jsreport/jsreport-text#3]
@pofider @bjrmatos  already did npm install jsreport-text and then this is my code
```js 
const client = require('jsreport-client')('http://localhost:5488')
app.get('/testreport',function(req,res){
      client.render({
//the short id is put as 'x' on purpose
      template: { 'shortid':'xxxxxx',recipe:"jsreport-text"},
    }).then((out) => {
       out.pipe(res)
})
})
```
But I get this error:
```If this is a custom recipe make sure it's properly installed from npm. Error: Recipe 'jsreport-text' not found. If this is a custom recipe make sure it's properly installed from npm.```
 All I wanted to do is to get a simple html report in form of plain text than can be downloaded as .txt.
I also used the 'text' recipie that comes with jsreport prebuilt but that gives response as raw html text. Any help/suggestions would be appreciated. Thank You.

**Comment by pofider** [comment]
The recipe name is just `text`.

```js
const client = require('jsreport-client')('http://localhost:5488')
app.get('/testreport',function(req,res){
      client.render({
//the short id is put as 'x' on purpose
      template: { 'shortid':'xxxxxx',recipe:"text"},
    }).then((out) => {
       out.pipe(res)
})
})
```
